name: Server

on:
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run linting
        run: pipenv run mypy src --check-untyped-defs
